# Generated by Django 3.2.21 on 2023-09-13 12:10

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('kosi_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='course',
            options={'ordering': ['price']},
        ),
        migrations.RemoveField(
            model_name='course',
            name='delivery_date',
        ),
        migrations.RemoveField(
            model_name='course',
            name='delivery_method',
        ),
        migrations.AddField(
            model_name='course',
            name='delivery',
            field=models.CharField(choices=[(1, 'Classroom'), (2, 'Online'), (3, 'All')], default=3, max_length=20),
        ),
        migrations.AddField(
            model_name='course',
            name='delivery_from',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='course',
            name='delivery_to',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
