# Generated by Django 3.2.21 on 2023-09-13 14:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kosi_app', '0002_auto_20230913_1210'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='delivery',
            field=models.CharField(blank=True, choices=[('Classroom', '1'), ('Online', '2'), ('All', '3')], default=3, max_length=20, null=True),
        ),
    ]
