# Generated by Django 3.2.21 on 2023-09-13 20:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kosi_app', '0003_alter_course_delivery'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='course_content',
            field=models.TextField(max_length=1500),
        ),
    ]
