# Generated by Django 3.2.21 on 2023-09-16 14:03

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('kosi_app', '0004_alter_course_course_content'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='course',
            options={'ordering': ['delivery_from']},
        ),
        migrations.AlterField(
            model_name='course',
            name='stars',
            field=models.ManyToManyField(blank=True, related_name='course_stars', to=settings.AUTH_USER_MODEL),
        ),
    ]
