# Generated by Django 3.2.21 on 2023-09-18 15:41

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('kosi_app', '0005_auto_20230916_1403'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='delivery_to',
        ),
        migrations.AlterField(
            model_name='course',
            name='stars',
            field=models.ManyToManyField(blank=True, related_name='course_star', to=settings.AUTH_USER_MODEL),
        ),
    ]
